version: "3"
 
services:
  db:
    image: postgres:latest
    container_name: postgresql 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
